### ISSUE TITLE
Update fixture ethnies

### ISSUE THREAD

**Issue by fadiga** [IBS-Mali/epi-droid#15]
Liste des ethnies du Mali.

**Comment by kabaassa** [comment]
Les ethenies du Mali
- [ ] Touareg
- [ ] Maures 
- [ ] Peuls
- [ ] Bambara
- [ ] Malinkes
- [ ] Dogon
- [ ] Senoufo
- [ ] Sonrai
- [ ] Sarakolle
- [ ] Bozo
- [ ] Somono
- [ ] Khassonke
- [ ] Arabe
- [ ] Toucouleur
